params:
  seed: 42

  env:
    clip_actions: 1.0
    clip_observations: 100.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False
  load_path: ''

  config:
    name: door_push_direct
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 2.0e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 100000000
    max_epochs: 4578
    save_best_after: 20
    save_frequency: 20
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 4096
    mini_epochs: 3
    critic_coef: 0.5
    clip_value: True
    seq_length: 16
    bounds_loss_coef: 0.0001

    central_value_config:
      minibatch_size: 4096
      mini_epochs: 3
      learning_rate: 2.0e-4
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.008
      clip_value: True
      normalize_input: True
      truncate_grads: True
      grad_norm: 1.0
      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [512, 256, 128]
          activation: elu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None
